<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Are you sure you want to release</name>
   <tag></tag>
   <elementGuidId>00ba0120-a90e-45ad-85c2-a710017a240f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-html-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-html-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>515afc48-3d6c-4768-8c27-3b54c5d0624c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>da3404d4-f801-4038-a8b1-9da7b696264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>4ec9b1be-3bd3-48f9-8ab8-c20a80030e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you sure you want to release WA1309 from this staff ?</value>
      <webElementGuid>fc8ca890-eb95-4c93-99fa-ba7926a4fc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-html-container&quot;)</value>
      <webElementGuid>da9b45b6-e743-4de9-876e-8afb1c391aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']</value>
      <webElementGuid>265a4614-beb2-439d-b797-59c994652217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>d3221949-f919-410d-b61e-8162a0bacb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steering Wheel Repair'])[3]/following::div[5]</value>
      <webElementGuid>2d4be67e-c9b2-4745-a81e-63f3d5e1453a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[4]</value>
      <webElementGuid>afab8e35-4890-4c73-9839-ee279f04b0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[4]</value>
      <webElementGuid>1162fe40-6098-411c-b50d-0cad43741440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Are you sure you want to release WA1309 from this staff ?']/parent::*</value>
      <webElementGuid>9e8c4841-eda9-49e2-9802-def4ea3ae74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div[2]</value>
      <webElementGuid>2ca33fb3-6e4c-4564-bc16-4f0f281781a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-html-container' and (text() = 'Are you sure you want to release WA1309 from this staff ?' or . = 'Are you sure you want to release WA1309 from this staff ?')]</value>
      <webElementGuid>4075d395-ca0b-4a08-bc9e-7ea4ff0169bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
