<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Entity_p-dropdown-trigger</name>
   <tag></tag>
   <elementGuidId>c894b992-93dd-4eb9-84ff-5025c2885f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_7-table']/thead/tr/th[4]/form/p-dropdown/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c16834fd-a41d-49d5-beca-43acd41e41bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6595801b-39aa-49a4-b1f3-1c73fa5c39ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dropdown trigger</value>
      <webElementGuid>c4351776-5d3d-427d-9336-6dfbd4adc660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>0d55f0ad-9658-4dd7-8ae8-1840f4f90838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger</value>
      <webElementGuid>9efd31e1-8434-4744-b58c-2d327b8e62c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fe2450f-44ce-4b89-9db5-c027be31eaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_7-table&quot;)/thead[@class=&quot;p-datatable-thead&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/th[4]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/p-dropdown[@class=&quot;p-element p-inputwrapper ng-pristine ng-valid ng-touched p-inputwrapper-focus&quot;]/div[@class=&quot;p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/div[@class=&quot;p-dropdown-trigger&quot;]</value>
      <webElementGuid>1dcf586e-cea5-44a8-9b94-e4bc1dba8872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_7-table']/thead/tr/th[4]/form/p-dropdown/div/div[2]</value>
      <webElementGuid>13cebe28-08c9-4faa-b070-753e40cdd15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Entity'])[1]/following::div[1]</value>
      <webElementGuid>460cf6c9-348c-4db7-9d97-2716c0d44f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejected Bill(s)'])[1]/following::div[11]</value>
      <webElementGuid>ca28d301-e22b-45ca-9245-9995b87dd074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGTB'])[1]/preceding::div[1]</value>
      <webElementGuid>fdb71c28-3483-46b4-a6d7-54dd603c067b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGIB'])[1]/preceding::div[1]</value>
      <webElementGuid>26884a8b-98d0-488c-968b-ae222c91a094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdown/div/div[2]</value>
      <webElementGuid>43a01485-a2a7-4659-8dce-72582c2b1224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
