<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DOWNLOAD</name>
   <tag></tag>
   <elementGuidId>20a4a9c5-6486-43ed-aba5-ad552b22a1a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.link-button.mt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 24/7 auto assist services with Etiqa SMILE app'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5eb24274-a6cc-414d-aecb-39d2853bc033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-button mt-2</value>
      <webElementGuid>aaa8e389-566f-4bc2-9a67-7377deb1f58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOWNLOAD</value>
      <webElementGuid>5f6653d1-4efa-468b-8410-21b12dbd3950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/ata-assessment-completed[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ata-relative ata-flex ata-flex-col ata-grow&quot;]/div[@class=&quot;ata-relative ata-z-1 ata-flex ata-flex-col ata-grow&quot;]/div[@class=&quot;ata-absolute ata-inset-0 ata-p-6 ata-overflow-auto ata-text-center&quot;]/div[@class=&quot;message-content border-round-md mt-5 ng-star-inserted&quot;]/div[@class=&quot;flex align-center p-3&quot;]/div[@class=&quot;flex-column ml-3 align-self-center&quot;]/div[@class=&quot;link-button mt-2&quot;]</value>
      <webElementGuid>95ee3ac7-64b8-42d0-8c90-cf939e647924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 24/7 auto assist services with Etiqa SMILE app'])[1]/following::div[1]</value>
      <webElementGuid>4d87d8a5-662e-4575-be05-f5061035fe34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I want to track my status'])[1]/following::div[6]</value>
      <webElementGuid>d7b411a3-925a-40dd-a74e-1cf4ce7797af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Request Details'])[1]/preceding::div[1]</value>
      <webElementGuid>53ce125e-ef5e-4993-b7bb-a3b4a86f1120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>1f8ef60e-fe67-48b1-b6d2-be850b0f6ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DOWNLOAD' or . = 'DOWNLOAD')]</value>
      <webElementGuid>c44ca223-a3e4-45dd-a65d-aeae30c93f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
