<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gear_click</name>
   <tag></tag>
   <elementGuidId>8a6c913a-6a86-4148-a1ce-d349df86f954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/partner-staff-detail/div[3]/div[2]/div/div[2]/p-checkbox/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p-checkbox.p-element.ng-valid.ng-dirty.ng-touched > div.p-checkbox.p-component.p-checkbox-checked > div.p-checkbox-box.p-highlight > span.p-checkbox-icon.pi.pi-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a419cce-186f-41a7-bd9a-0e8b61cc5e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-icon pi pi-check</value>
      <webElementGuid>95fd0c1d-4fc9-4eaa-ad53-8697fb84c446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>pi pi-check</value>
      <webElementGuid>4a2360a2-bde2-4e22-b09c-80f2aa35f921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overflow-hidden lg:overflow-auto&quot;]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-partner-staff[@class=&quot;ng-star-inserted&quot;]/partner-staff-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-column bg-color&quot;]/div[@class=&quot;p-2 grid&quot;]/div[@class=&quot;p-3 md:col-8 bg-white hidden-xs&quot;]/div[@class=&quot;ng-star-inserted&quot;]/partner-staff-detail[1]/div[@class=&quot;py-4 border-bottom-1 grid&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;flex flex-column float-right sm:mr-2 md:mr-6 lg:mr-8&quot;]/div[@class=&quot;p-field-checkbox staff-checkbox pb-3 grid ng-star-inserted&quot;]/p-checkbox[@class=&quot;p-element ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;p-checkbox p-component p-checkbox-checked&quot;]/div[@class=&quot;p-checkbox-box p-highlight&quot;]/span[@class=&quot;p-checkbox-icon pi pi-check&quot;]</value>
      <webElementGuid>ec3fddae-db5b-4872-a50a-550b022795ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/partner-staff-detail/div[3]/div[2]/div/div[2]/p-checkbox/div/div[2]/span</value>
      <webElementGuid>861789e4-1e34-429c-ac44-9f4517e77797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
