<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wheel_click</name>
   <tag></tag>
   <elementGuidId>46e736ef-d9d6-42d7-9c21-8abc0c99dc77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/partner-staff-detail/div[3]/div[2]/div/div[3]/p-checkbox/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p-checkbox.p-element.ng-valid.ng-dirty.ng-touched > div.p-checkbox.p-component.p-checkbox-checked > div.p-checkbox-box.p-highlight > span.p-checkbox-icon.pi.pi-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e52f6dbc-feb6-415a-bb3c-0eed48860b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-icon pi pi-check</value>
      <webElementGuid>a73da4d6-41fb-4e8d-ab41-ed0d276181f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>pi pi-check</value>
      <webElementGuid>e99077f8-c5f4-46fb-a2c6-27e98250524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overflow-hidden lg:overflow-auto&quot;]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-partner-staff[@class=&quot;ng-star-inserted&quot;]/partner-staff-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-column bg-color&quot;]/div[@class=&quot;p-2 grid&quot;]/div[@class=&quot;p-3 md:col-8 bg-white hidden-xs&quot;]/div[@class=&quot;ng-star-inserted&quot;]/partner-staff-detail[1]/div[@class=&quot;py-4 border-bottom-1 grid&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;flex flex-column float-right sm:mr-2 md:mr-6 lg:mr-8&quot;]/div[@class=&quot;p-field-checkbox staff-checkbox pb-3 grid ng-star-inserted&quot;]/p-checkbox[@class=&quot;p-element ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;p-checkbox p-component p-checkbox-checked&quot;]/div[@class=&quot;p-checkbox-box p-highlight&quot;]/span[@class=&quot;p-checkbox-icon pi pi-check&quot;]</value>
      <webElementGuid>8160b86c-c054-4e7b-a501-2d5ca889ac95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/partner-staff-detail/div[3]/div[2]/div/div[3]/p-checkbox/div/div[2]/span</value>
      <webElementGuid>31124372-e5fd-409a-986b-d8d895b18f88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
