<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_feedback</name>
   <tag></tag>
   <elementGuidId>827dac53-4e67-4014-a1d0-c980e8b4ce8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Tracking'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4823d92-94e9-4f54-9fd8-cc7b94e2a6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ata-flex ata-items-center ata-p-3</value>
      <webElementGuid>10b7b5ec-206a-419b-a2b4-81d22bd143c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/rating/verify</value>
      <webElementGuid>d112c02f-378c-4c66-a562-c33abc0c2b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auto/rating/verify</value>
      <webElementGuid>3ef575c5-3cc6-4c5b-be1b-25bdb393f709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share feedback</value>
      <webElementGuid>3e98e54d-b492-495d-a4eb-4fb2f42d9d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/atau-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ata-p-6 -ata-mt-40&quot;]/div[@class=&quot;ata-mt-6&quot;]/div[@class=&quot;ata-grid ata-grid-cols-2 ata-gap-6&quot;]/div[@class=&quot;ata-card&quot;]/a[@class=&quot;ata-flex ata-items-center ata-p-3&quot;]</value>
      <webElementGuid>840ada56-e564-4e71-8618-c9eb0a927110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Tracking'])[1]/following::a[1]</value>
      <webElementGuid>56550671-6320-468c-a079-cac3d0b6aa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick links'])[1]/following::a[2]</value>
      <webElementGuid>72de93d5-8147-478f-8f7e-17193dfa70b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locate our panel'])[1]/preceding::a[1]</value>
      <webElementGuid>9f390e0c-2eb0-40ab-a67a-be09fc316728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auto/rating/verify')]</value>
      <webElementGuid>b37d95a9-6fcb-479f-9727-27ecff4bd1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>28c94282-3649-424f-b62b-ea91ebac4e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auto/rating/verify' and (text() = 'Share feedback' or . = 'Share feedback')]</value>
      <webElementGuid>eabe49be-3ece-45d6-99fc-888393a13423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
