<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonlink_DOWNLOAD</name>
   <tag></tag>
   <elementGuidId>ddabc75d-cf1f-4e61-bc72-6416c9d5ac76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.p-element.p-button.link-button.p-2.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 24/7 auto assist services with Etiqa+ app'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9e5e14e-45c7-4a1b-be94-1d1953b29b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://eti.qa/autodownload</value>
      <webElementGuid>a90fc4c5-5d10-462c-a125-cc69cc9ec081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>148bbf39-7180-436f-912f-df69e14ee233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>DOWNLOAD</value>
      <webElementGuid>4081b577-0abf-45c2-a8e1-d61b98a992fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button link-button p-2 p-component</value>
      <webElementGuid>4dfedabe-1bd2-460b-93c9-98e13872af44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-label</name>
      <type>Main</type>
      <value>DOWNLOAD</value>
      <webElementGuid>dd95140a-005e-452e-853d-03e2e3cc2686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOWNLOAD</value>
      <webElementGuid>388926d5-af92-4852-a9b6-4f6bd75be298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/p-messages[@class=&quot;p-element ng-tns-c3316150596-2 ng-star-inserted&quot;]/div[@class=&quot;p-messages p-component ng-tns-c3316150596-2 custom-message&quot;]/div[@class=&quot;ng-tns-c3316150596-2 p-message p-message-info ng-star-inserted&quot;]/div[@class=&quot;p-message-wrapper ng-tns-c3316150596-2&quot;]/div[@class=&quot;flex justify-content-center align-content-center w-full ng-star-inserted&quot;]/div[@class=&quot;ml-3 align-self-center&quot;]/a[@class=&quot;p-element p-button link-button p-2 p-component&quot;]</value>
      <webElementGuid>d3d10151-dd01-4f8c-a872-92751d3db40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 24/7 auto assist services with Etiqa+ app'])[1]/following::a[1]</value>
      <webElementGuid>1c540481-1142-4281-8af1-5ed23f77d7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::a[1]</value>
      <webElementGuid>eb0f6642-eeaf-40ec-997e-27c7f5d2e1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etiqa Auto Assist Care'])[1]/preceding::a[2]</value>
      <webElementGuid>38291c87-ae59-4e37-9592-bdb240e3a080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://eti.qa/autodownload')]</value>
      <webElementGuid>10d5afab-06e1-4d7c-a205-575fc05edf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>4993608a-324e-48d3-8c09-25d3f4e80c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://eti.qa/autodownload' and (text() = 'DOWNLOAD' or . = 'DOWNLOAD')]</value>
      <webElementGuid>ac04ccb0-d27b-4bdc-b88c-1a90a6c9a149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
