<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_call_SgThaiBru</name>
   <tag></tag>
   <elementGuidId>dc0499c3-bd08-47d7-9fc1-b1c4a1192a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca45b01a-4221-4cf0-b488-eb9e80ff76b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e767734-a91f-469a-932f-4f5bff631a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>pi pi-phone</value>
      <webElementGuid>3896e3e3-33e3-4303-bdd2-7287755dda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button-rounded p-button-danger p-button p-component p-button-icon-only</value>
      <webElementGuid>4ad10ce1-d5d1-4b95-814d-7a291d37632a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-icon</name>
      <type>Main</type>
      <value>pi pi-phone</value>
      <webElementGuid>7162c570-ad72-4d23-9ef4-19e030159f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/p-dialog[@class=&quot;p-element ng-tns-c98-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c98-1 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker p-dialog-bottom ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c98-1 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c98-1 p-dialog-content&quot;]/div[@class=&quot;ata-flex ata-items-center ng-tns-c98-1&quot;]/div[@class=&quot;ata-pl-6&quot;]/button[@class=&quot;p-element p-button-rounded p-button-danger p-button p-component p-button-icon-only&quot;]</value>
      <webElementGuid>aeffb5ef-0c4c-4a4c-a722-8c8bfd7a7106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>001942e8-cf64-47c7-8a5c-dcd8e5aabbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore, Thailand &amp; Brunei'])[1]/following::button[1]</value>
      <webElementGuid>ebea865c-8160-41f4-ac7c-f1d1f2d94299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[1]/following::button[2]</value>
      <webElementGuid>e921bf92-e1cd-4796-9ad9-72495ca1b0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>74ba0b8c-1466-44d9-9935-186260d8f498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>caa6e8f8-74f2-4f78-a297-23dc8975c5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>9607cc8b-e286-4749-8b47-86138dfe7580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>acbe3d46-2bc3-4bc5-821b-649b9cf62d0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
