<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vehicle make</name>
   <tag></tag>
   <elementGuidId>a2a55c1a-ec2c-4136-b7d3-4b30b1af539e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-dropdown-filter.p-inputtext.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b37b470-16fc-411f-aeac-13bdb37b0bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d079c0a4-d9e5-4c35-8df5-36d0d806c975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7a11674-31bd-4f06-8201-1520a4cac0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-filter p-inputtext p-component</value>
      <webElementGuid>b9b3357f-a577-470e-ad52-11d84249f146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>p-highlighted-option</value>
      <webElementGuid>25f8b9df-559b-4ddb-8bf2-87a146e22bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;content-data&quot;]/app-case-tab[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;flex ng-star-inserted&quot;]/div[@class=&quot;w-8 pr-5&quot;]/app-case-new[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/p-card[@class=&quot;p-element&quot;]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;p-field&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col&quot;]/p-dropdown[@class=&quot;p-element p-inputwrapper ng-pristine ng-invalid ng-star-inserted ng-touched p-inputwrapper-focus&quot;]/div[@class=&quot;w-full p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/p-overlay[@class=&quot;p-element ng-tns-c71-22 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c71-22 p-overlay p-component ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayContentAnimation ng-tns-c71-22 p-overlay-content ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-header ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-filter-container ng-star-inserted&quot;]/input[@class=&quot;p-dropdown-filter p-inputtext p-component&quot;]</value>
      <webElementGuid>eac0feba-ae0f-4800-9e0c-e0b2d72c310d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>f509b8ca-7c95-4c3d-b4a4-72f674a3f279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-overlay/div/div/div/div/div/input</value>
      <webElementGuid>6e35841a-0e3f-4a0a-9966-1763f74bbe9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>787d8dea-3c36-453d-860c-adab5e93f217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
