<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ratings 4 Details Suggestions</name>
   <tag></tag>
   <elementGuidId>84e716c8-bd40-45ba-bd6c-765d4e488383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c151-52 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c151-52 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c151-52 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c151-52&quot;]/ata-dialog-rating-create[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;mt-5&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtextarea.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div[4]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>11827dc3-7a6f-499c-97d2-c83311337e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>34c0194c-0cc7-4b10-b03b-03629a040b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>9a402ceb-4814-4ce8-87ef-c7bbf2af874a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a3687e33-f47c-4ca0-928e-6085b7852b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>7fa9f8ef-e3b6-45ad-b3aa-efd6f63e6c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c151-52 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c151-52 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c151-52 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c151-52&quot;]/ata-dialog-rating-create[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;mt-5&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>c9474393-dd73-4aad-8d03-27c58921ba2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/textarea</value>
      <webElementGuid>a47e7e6f-b85b-4c68-a8c9-f1121cfec780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
