<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ratings4_Suggestions</name>
   <tag></tag>
   <elementGuidId>f8479b0d-1da1-417b-8030-dd7afaef6f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c3177718326-84 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c3177718326-84 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c3177718326-84 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c3177718326-84&quot;]/ata-dialog-rating-create[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mt-5&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtextarea.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/p-dynamicdialog/div/div/div[2]/ata-dialog-rating-create/form/div[4]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1bef6edd-81e6-42a8-a447-e074acd4da02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>720b6027-1d27-41d4-a3ce-2beff34a5010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>fdc23984-a89e-4e2b-8e19-06c4ce94df7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9ab62f0e-0ad7-4bff-b206-425378a8da21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>98bc1f3e-b035-4811-bd1c-23a7b35e61ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c3177718326-84 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c3177718326-84 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c3177718326-84 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c3177718326-84&quot;]/ata-dialog-rating-create[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mt-5&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>9dc2d401-0b6a-4664-b6ba-a4d13b08bde5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/textarea</value>
      <webElementGuid>45b0e751-b61e-4794-ab2b-a467997e7685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
