<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ratings 4 Details Suggestions</name>
   <tag></tag>
   <elementGuidId>84e716c8-bd40-45ba-bd6c-765d4e488383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtextarea.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div[4]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>71f95fb4-1de8-4d82-9647-1c25207b3107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fe2beeb9-071b-4a92-9681-d3ae4d80fe78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>8ac8e580-eb2a-4ae0-9cca-0335052f4135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cd7d1d1d-3ab4-4c8d-9fcd-af9ec628222c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>suggestion</value>
      <webElementGuid>07d7a87d-65ac-4205-82fe-ead4f4a57d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c151-52 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c151-52 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c151-52 p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c151-52&quot;]/ata-dialog-rating-create[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;mt-5&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>f4770e13-601d-45d1-9622-e3fceba2d2da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/textarea</value>
      <webElementGuid>9e91ec09-0645-4fbe-8b24-8fc409cc5a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
