<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ratings 2_0 (Not Likely)</name>
   <tag></tag>
   <elementGuidId>c740505d-3353-4e6b-840d-52ab2efd83c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pr_id_57_list']/p-dropdownitem[1]/li/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '0' or . = '0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-dropdown-item > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24459ac9-ceed-4743-aec4-ff74c74cd877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>164d3174-9c92-4089-862a-0e9ae317392d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f2c3286-4daf-49aa-b42f-dacfd2f968f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_57_list&quot;)/p-dropdownitem[@class=&quot;p-element ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-dropdown-item&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>b8ac2f1f-005a-4736-83bb-ccdf45f9f02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_57_list']/p-dropdownitem[1]/li/span</value>
      <webElementGuid>92c88c3b-a1d8-42d4-b65b-87206e1dfe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How likely are you to recommend Etiqa Auto Assist Care (EAAC) to your family and friends?'])[2]/following::span[3]</value>
      <webElementGuid>b39776cc-5e5a-49b8-8327-055a8331368b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy'])[1]/following::span[4]</value>
      <webElementGuid>275933db-45e8-4ba3-85bc-5b2d191d83cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How was the waiting time?'])[2]/preceding::span[11]</value>
      <webElementGuid>d757dccb-cb60-4ce5-a902-16bcc0949153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[1]/preceding::span[11]</value>
      <webElementGuid>c050c660-a856-4ac9-b595-1eac7760e16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>986d8958-4d22-4f28-9ec7-19bb638e56dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem/li/span</value>
      <webElementGuid>a3476edb-8818-4416-ab60-88302d201530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0' or . = '0')]</value>
      <webElementGuid>9b9e3cdd-e3ca-4701-86c8-3510c692b168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
