<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Agent Sub Type</name>
   <tag></tag>
   <elementGuidId>1ca54e31-536e-47dc-b706-d75fb3528b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='agentSubType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agentSubType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>6e049e67-592e-4a00-82fb-f4afd0840484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agentSubType</value>
      <webElementGuid>80226900-65d8-42cf-8324-5279e7a628d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agent Sub Type</value>
      <webElementGuid>1e44d975-46d3-4804-b1d3-6f8e2133e191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agentSubType&quot;)</value>
      <webElementGuid>a23a67a7-88f8-4da9-b6c3-5d4e113ec44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='agentSubType']</value>
      <webElementGuid>64e50e00-1ccf-4018-aa03-a9b0fd5e1b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_65-table']/thead/tr/th</value>
      <webElementGuid>d6fa21af-fbd0-467d-939e-8e114347b476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Franchise'])[1]/following::th[1]</value>
      <webElementGuid>fafd237e-f5df-4b2e-817b-8b958241fb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v3.10.0'])[1]/following::th[1]</value>
      <webElementGuid>edfd9386-4ed2-45d7-a40e-88785c21df19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::th[1]</value>
      <webElementGuid>edb88fb0-22dc-4cff-abc5-ed60361f2c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programme Info'])[1]/preceding::th[2]</value>
      <webElementGuid>294e57b4-7370-40e7-8b10-eb76d1e64724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agent Sub Type']/parent::*</value>
      <webElementGuid>d05277e5-cd67-4095-ae6b-df7ac28d3082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>c98a7a87-5d12-4c22-9bd3-771a95a1ee94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'agentSubType' and (text() = 'Agent Sub Type' or . = 'Agent Sub Type')]</value>
      <webElementGuid>ba1efd39-47a3-4a07-87c7-0cdeaa2f3127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
