<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Resolved</name>
   <tag></tag>
   <elementGuidId>7468d4f4-32f3-471a-a8fe-2d754631b452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_55-table']/tbody/tr[4]/td[5]/ata-case-status/p-tag/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-tag-resolved.p-tag.p-component > span.p-tag-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a79413bc-5f33-4328-b758-5778e33c2f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tag-value</value>
      <webElementGuid>fd40f26f-11fe-42f4-8081-5c643f226336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resolved</value>
      <webElementGuid>fae4fa53-4c96-472a-afdd-ef6dd3471808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_55-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[5]/ata-case-status[1]/p-tag[@class=&quot;p-element&quot;]/span[@class=&quot;p-tag-resolved p-tag p-component&quot;]/span[@class=&quot;p-tag-value&quot;]</value>
      <webElementGuid>b298a4d2-cdc3-4d8f-9f40-9de39dc988ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_55-table']/tbody/tr[4]/td[5]/ata-case-status/p-tag/span/span</value>
      <webElementGuid>17d9b04b-1205-454a-9001-38c2bf43442e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JSF7791'])[4]/following::span[5]</value>
      <webElementGuid>a6859efc-89b5-4607-8a22-a6e1a568d648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[6]/following::span[5]</value>
      <webElementGuid>ffb7bfc6-9d9c-4846-9feb-32080dd15eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[7]/preceding::span[1]</value>
      <webElementGuid>3ab3d9eb-2ac9-46f8-aeea-85feaecf0d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[8]/preceding::span[1]</value>
      <webElementGuid>23c88959-090e-45db-bf9a-7cf548d55ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resolved']/parent::*</value>
      <webElementGuid>68cf53f3-c471-4500-8a6c-1c53b9bce941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/ata-case-status/p-tag/span/span</value>
      <webElementGuid>67e8b2b3-3a88-4a6e-a8ae-3b5073f6fd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Resolved' or . = 'Resolved')]</value>
      <webElementGuid>29042ad8-abba-4665-901f-d4e19953463d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
