<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HaziqWA1309 (1)</name>
   <tag></tag>
   <elementGuidId>f7f3cc11-aa9f-4451-add1-f1915f5848bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'p-accordiontab-107' and (text() = '  HaziqWA1309' or . = '  HaziqWA1309')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-accordiontab-107']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-accordiontab-107</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>814041ba-ec59-4e87-972c-4621f153e142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6a95a5e7-a5cb-436f-9eee-bffa5b7dec0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-accordion-header-link ng-tns-c73-112</value>
      <webElementGuid>d15aedbd-5d3c-440a-a870-a7deec76ad80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b44ee5cd-ceae-4062-a18f-948b4763d42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-accordiontab-107</value>
      <webElementGuid>03d4dc76-0b14-422f-8bdb-08219f35d68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-accordiontab-107-content</value>
      <webElementGuid>4d4dd44e-e334-4215-81e5-257512ab3aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  HaziqWA1309</value>
      <webElementGuid>37375ee4-f969-4e67-9d51-7bc57985c094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-accordiontab-107&quot;)</value>
      <webElementGuid>42b29226-b950-4076-a043-509a5152a7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-accordiontab-107']</value>
      <webElementGuid>feae721a-4c34-47c2-9351-e924975bef20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/following::a[1]</value>
      <webElementGuid>bcd46936-9480-451b-8e3b-fa6bc8c636a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abdul Hakim'])[1]/following::a[1]</value>
      <webElementGuid>10284f70-5391-4479-8c28-0de84dd2d113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-accordion[2]/div/p-accordiontab/div/div/a</value>
      <webElementGuid>dfc5de80-0323-481b-acce-bb2c69ea81ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-accordiontab-107' and (text() = '  HaziqWA1309' or . = '  HaziqWA1309')]</value>
      <webElementGuid>0dbae8f4-a790-4227-95fa-eb294fcc0e04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
