<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Back Main ATAU</name>
   <tag></tag>
   <elementGuidId>ba491d31-3bd0-4b7f-bdf7-3e41af8671b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;eaac-logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='eaac-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1aeb6f35-c6e9-4ef5-968b-abf94195c50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eaac-logo</value>
      <webElementGuid>8393d475-d709-4a03-b436-440766760e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/EAAC.svg</value>
      <webElementGuid>aae7c835-cdab-4fd0-acd4-d2bf78be5f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/div[1]/header[@class=&quot;flex header&quot;]/a[@class=&quot;header-logo&quot;]/img[1]</value>
      <webElementGuid>0207c600-d8e7-4bbc-8bd0-f638f541181c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='eaac-logo']</value>
      <webElementGuid>94248585-ba46-4561-933c-68d0851a019a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>9e87bf32-2153-4726-ade9-81a3219a2ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'eaac-logo' and @src = 'assets/images/EAAC.svg']</value>
      <webElementGuid>c2a7af6c-2775-4793-9c71-c5978b85e596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
