<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username</name>
   <tag></tag>
   <elementGuidId>ece782ac-6195-4507-8cc7-77c556c8a95d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.ng-pristine.ng-invalid.ng-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b36d8f0f-6218-476a-9559-fecb6588e57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>10d41568-2b97-4fd1-990c-4705a7b91ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>300e67d9-eb5c-4767-91c0-7790262403d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>5812304e-f936-43ed-9304-3c26ed503fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>dc44330d-7064-4817-9c24-161c033a43f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>c6b0361e-237a-4d3c-844f-64b1f300cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content layout-content-login&quot;]/div[@class=&quot;content-data&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;login-form ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;p-field mb-3&quot;]/input[@class=&quot;p-inputtext p-component p-element ng-pristine ng-invalid ng-touched&quot;]</value>
      <webElementGuid>2e383149-b847-42e8-a727-45cbf289e360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>40848639-2c3a-4bef-ba1c-71612731b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c766e15f-eb8b-4fc0-80b9-b15fbf314a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Username' and @type = 'text']</value>
      <webElementGuid>15ae8a54-5b0d-4c54-b73b-aa028655c28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
