<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SearchFilter</name>
   <tag></tag>
   <elementGuidId>e499f0e5-f360-4593-92b8-aba08f3f57bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-button-primary.w-12.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcc61815-81e5-4d77-ba40-061706ab68ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7f1c2bd-f45b-45d1-9ec2-9449ee8c9556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6f024d77-91af-4f9d-b09a-8e16d68bf021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button-primary w-12 p-button p-component</value>
      <webElementGuid>6cf43cae-71d8-4369-ad2e-e97a9ab228f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>2d29b075-a47f-4512-ac48-8efcd7e2a85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>585efe17-62af-44d1-aba2-0525f35f7316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;content-data&quot;]/ata-dashboard-cases[@class=&quot;ng-star-inserted&quot;]/ata-dashboard-case-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-8&quot;]/ata-dashboard-case-list-filter[1]/div[@class=&quot;surface-0 p-4&quot;]/form[@class=&quot;mb-2 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;grid nested-grid&quot;]/div[@class=&quot;col-fixed w-10rem py-1&quot;]/button[@class=&quot;p-element p-button-primary w-12 p-button p-component&quot;]</value>
      <webElementGuid>f6dcbc58-a2e3-4621-986c-031cdb2ea11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>be5cb8db-5976-448e-a111-741974b63691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Number'])[1]/following::button[1]</value>
      <webElementGuid>c8769cd4-c169-40d5-89ac-68055a545b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search By'])[1]/following::button[1]</value>
      <webElementGuid>112a71de-12e4-4792-85ad-e357915491c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add filter'])[1]/preceding::button[1]</value>
      <webElementGuid>ce096467-bd27-41cd-b418-8c6deb0b3ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5ddd3361-181e-4be3-b0be-fc8e7b1176ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>90ed5133-c3e9-4636-8a67-90d04697dc1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
