<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputFilter_Vehicle Number</name>
   <tag></tag>
   <elementGuidId>3c9b0849-8a68-4023-a49c-3d61807e05d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.w-12.ng-invalid.ng-star-inserted.ng-pristine.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b68175df-7844-4dfc-9a75-c34f40bf8f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea661538-ab14-4c12-8052-0516fdc064c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>08899ab3-5454-4562-8969-da9cc468cd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element w-12 ng-invalid ng-star-inserted ng-pristine ng-touched</value>
      <webElementGuid>0aaaf3de-4440-470c-acd8-5285ec37704a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>5251d206-032b-4b62-ae43-f901e9998c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;content-data&quot;]/ata-dashboard-cases[@class=&quot;ng-star-inserted&quot;]/ata-dashboard-case-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-8&quot;]/ata-dashboard-case-list-filter[1]/div[@class=&quot;surface-0 p-4&quot;]/form[@class=&quot;mb-2 ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;grid nested-grid&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-3 py-1 ng-star-inserted&quot;]/input[@class=&quot;p-inputtext p-component p-element w-12 ng-invalid ng-star-inserted ng-pristine ng-touched&quot;]</value>
      <webElementGuid>e3d6de57-cf14-4a54-95bd-f365ba9c91ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>e59fab53-319c-405a-92e5-49eca276c7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>656399c9-49c6-4fcb-8728-eea00e7dce5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>15549658-0745-4b14-bac0-0f1f6746f685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
