<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nearest</name>
   <tag></tag>
   <elementGuidId>dd7ba117-ccc2-439e-9cc5-807958332b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-button.btn1.active.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2aff45fe-e620-4e99-af9e-fccc6fdbb84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1de6debf-a37d-4d96-ad7b-5065cd83a3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Nearest...</value>
      <webElementGuid>e578b8d8-b0fc-4886-ae1e-d3e343fc2beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button btn1 active p-component</value>
      <webElementGuid>3e9e9143-7d1b-4f76-ba4f-3aeb9e969266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-label</name>
      <type>Main</type>
      <value>Nearest...</value>
      <webElementGuid>09bf3374-eeb6-496e-8c7b-d025a3f8ac9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nearest...</value>
      <webElementGuid>7bc129d9-3923-4179-8ac8-768628112bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-partner-cases[@class=&quot;ng-star-inserted&quot;]/partner-case-detail[@class=&quot;ng-star-inserted&quot;]/p-dialog[@class=&quot;p-element dialog-partner ng-tns-c98-7 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c98-7 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c98-7 p-dialog p-component p-dialog-draggable p-dialog-resizable ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c98-7 p-dialog-content&quot;]/div[@class=&quot;flex flex-column mb-5 ng-tns-c98-7&quot;]/div[@class=&quot;w-full pt-2&quot;]/div[@class=&quot;mt-4 div1&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col btn1-col&quot;]/button[@class=&quot;p-element p-button btn1 active p-component&quot;]</value>
      <webElementGuid>d9aa8c66-7b77-40a0-9e17-daf74b122543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>1506f874-127b-4a59-aa01-bedc09b8bc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign the driver for this case'])[1]/following::button[1]</value>
      <webElementGuid>8b97da9b-1f8e-4d6a-85ee-ea9260fa94dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Driver'])[1]/following::button[1]</value>
      <webElementGuid>2338866c-ac5b-4819-b6ea-695fde197ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Drivers'])[1]/preceding::button[1]</value>
      <webElementGuid>26a65568-100d-4653-babd-a90ff83033ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>2b5ce019-3dd7-43cb-8581-3f5d92b088ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Nearest...' or . = 'Nearest...')]</value>
      <webElementGuid>afe2ed00-fd72-469f-9604-b86fdea802c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
