<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Distance</name>
   <tag></tag>
   <elementGuidId>274ae362-7ded-417f-a04b-38ea5622bf0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ata-flex.ata-items-center.ata-px-6.ata-py-4.ata-bg-slate-100.ata-cursor-pointer.ata-border-y.ata-border-slate-200</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b67cd307-5f51-4628-b8c8-7fcb9cb64853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ata-flex ata-items-center ata-px-6 ata-py-4 ata-bg-slate-100 ata-cursor-pointer ata-border-y ata-border-slate-200</value>
      <webElementGuid>4d415dc2-0a50-4b05-aaf5-be7dd65393d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Distance</value>
      <webElementGuid>82e34bf2-2dc9-4d8a-8100-b0fcd73e25e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;ng-trigger ng-trigger-panelState ng-tns-c121-6 p-sidebar p-sidebar-active p-sidebar-right ng-star-inserted&quot;]/div[@class=&quot;p-sidebar-content ng-tns-c121-6&quot;]/div[@class=&quot;-ata-mx-4 ng-star-inserted&quot;]/div[1]/a[@class=&quot;ata-flex ata-items-center ata-px-6 ata-py-4 ata-bg-slate-100 ata-cursor-pointer ata-border-y ata-border-slate-200&quot;]</value>
      <webElementGuid>039ccd55-279b-4fda-93ca-202d2b904410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::a[1]</value>
      <webElementGuid>cbcba241-17f5-4ea0-81ad-a12ab9c28e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::a[1]</value>
      <webElementGuid>939635f3-44ed-4c23-9ff5-f41d84f0d4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::a[1]</value>
      <webElementGuid>2fa8f978-ffe0-4b46-b61e-ac416c7c19ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>5974c0a6-e0f2-4ae9-8a8a-e57f8b2eaa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Distance' or . = 'Distance')]</value>
      <webElementGuid>43a225d0-0e0a-4568-a7c6-b5f20d5d340a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
