<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print</name>
   <tag></tag>
   <elementGuidId>b6ac247d-cac3-4147-9cb1-41e61583341e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload invoice with signatory'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.button-plain.p-button.p-component > span.p-button-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c975ee94-dd82-4421-ac30-d641be0a8a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>18037e46-f9bf-4985-8e02-5779c572e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>f052b90b-bb0f-49aa-84ad-346d3bcc1523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overflow-hidden lg:overflow-auto&quot;]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-work-orders[@class=&quot;ng-star-inserted&quot;]/ata-work-order-detail[@class=&quot;ng-star-inserted&quot;]/partner-invoice-footer[1]/div[@class=&quot;temp-footer inline-flex grid no-print justify-content-between&quot;]/div[@class=&quot;flex justify-content-end flex-wrap btn-right&quot;]/div[@class=&quot;pr-2 ng-star-inserted&quot;]/button[@class=&quot;p-element button-plain p-button p-component&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>7c7a1459-d1a3-4514-a4a6-20972d8acfa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload invoice with signatory'])[1]/following::span[1]</value>
      <webElementGuid>8b54861f-760e-4a1e-b6ca-f32cdf74df0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::span[2]</value>
      <webElementGuid>43ab2ab6-e4bb-41e2-a861-45c1710ab533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[1]</value>
      <webElementGuid>df6e427b-98ad-406c-960c-6719c26dbb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::span[2]</value>
      <webElementGuid>89372203-e224-4f66-9db6-080b277ec7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print']/parent::*</value>
      <webElementGuid>4866e3f1-de77-4b67-8e44-e095dbc7ff6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>92e69676-9c8b-41cf-8a3e-85e5ef04aa9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Print' or . = 'Print')]</value>
      <webElementGuid>4935ee00-0fa1-4157-9ebc-0168db50289f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
