<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload</name>
   <tag></tag>
   <elementGuidId>716f04be-d17e-4ccc-bcbc-07ef03dff05c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Upload' or . = 'Upload')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 90.00'])[3]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-button-primary.px-6.text-left.p-button.p-component > span.p-button-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>057fcbb2-3ab2-4959-b275-ca534cc0b0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>205c0b60-f533-4e90-9438-768bf9296a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>273b13c6-dddd-48b2-8a72-ae44c0b0012c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-work-orders[@class=&quot;ng-star-inserted&quot;]/ata-work-order-detail[@class=&quot;ng-star-inserted&quot;]/partner-invoice-footer[1]/div[@class=&quot;temp-footer inline-flex grid no-print justify-content-between&quot;]/div[@class=&quot;flex ng-star-inserted&quot;]/button[@class=&quot;p-element p-button-primary px-6 text-left p-button p-component&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>cdff1187-b2b2-4b88-99c4-89c551686caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 90.00'])[3]/following::span[2]</value>
      <webElementGuid>49d771dc-e655-492f-ae35-164a7b883f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 0.00'])[4]/following::span[2]</value>
      <webElementGuid>f8f91286-cbd4-4b13-8227-54390832f5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload invoice with signatory'])[1]/preceding::span[1]</value>
      <webElementGuid>4db64ecc-d21d-4711-a4fa-41f42dbdeb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::span[2]</value>
      <webElementGuid>845d169c-3a4e-4ad0-a58f-c96ba6d03cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>ad20c4d9-7304-42e4-a9d0-c95585929611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>2694392b-2d82-40a6-823c-d5bdfe945533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>64314631-e060-48e9-a090-9fa4fe111cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
