<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_lottie1</name>
   <tag></tag>
   <elementGuidId>f6ae53aa-33ff-4ed1-b401-577affa8d8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-lottie.ata-mb-4.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe694804-acd1-4bf3-9768-6329dd9220d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/lottie/finding-service-provider.gif</value>
      <webElementGuid>2d5ae5ee-a98f-436e-8d58-d1fe3e7387dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-lottie ata-mb-4 ng-star-inserted</value>
      <webElementGuid>335e7b4c-2176-4ef0-ae72-ce4ee276ab88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/atau-tracking[@class=&quot;ng-star-inserted&quot;]/atau-tracking-finding-service[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ata-flex ata-flex-col ata-grow ata-p-6&quot;]/img[@class=&quot;img-lottie ata-mb-4 ng-star-inserted&quot;]</value>
      <webElementGuid>a4a81a54-6a7d-4785-b388-d7c0ba58c9fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e67d55f9-f530-4d79-84f5-a4d5f4fc3aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/lottie/finding-service-provider.gif']</value>
      <webElementGuid>978d6f2b-4701-4876-8660-4c52bdb4d1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
