<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address_1</name>
   <tag></tag>
   <elementGuidId>a5675239-fc0a-4f03-bf65-f044c91ff470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>5a829ec3-f259-4b72-af9b-926293b1232e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>d9b2d9ea-5969-4345-9911-ba5723e35c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>psortablecolumn</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>049cedd7-adcf-4a9b-bbea-b039cea5c774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-sortable-column</value>
      <webElementGuid>6f412fc3-037f-420d-9578-b349dc58db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>b3dc52d0-c266-4825-8496-3b5c1e1ce21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d20e691e-2cde-4a92-a1ba-ef319f1f33ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>3a3bfb9b-fc39-40f0-874e-e52c96e2cb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>0aada0b1-6dd0-4298-926f-02dc1380ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Address 1</value>
      <webElementGuid>64276896-9463-419b-9fa8-b8bc72c9011f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
      <webElementGuid>c9c7ec46-caba-4b25-bbf6-45dc7782f7b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='address']</value>
      <webElementGuid>23086ae5-b7a9-4917-927c-b3eee977226b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_16-table']/thead/tr/th[5]</value>
      <webElementGuid>756642f9-ba07-47eb-b0bd-495b9b2a2e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::th[1]</value>
      <webElementGuid>516239d1-e577-47ca-927a-1e6937529f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Category'])[1]/preceding::th[4]</value>
      <webElementGuid>8b97e128-fada-4cd7-ac53-1bdd1a108e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Address']/parent::*</value>
      <webElementGuid>19052956-72df-46aa-b900-568a304a69d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]</value>
      <webElementGuid>4b749479-f7d8-4e7a-9ee1-22231285931f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'address' and (text() = ' Address 1' or . = ' Address 1')]</value>
      <webElementGuid>b399ee69-3ca8-45b5-ba10-5a4ffd8a7acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
