<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateTo</name>
   <tag></tag>
   <elementGuidId>9d1efbeb-9993-41a7-bc54-0454d801a3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'DD/MM/YY']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c81-6.w-10rem.p-inputtext.p-component.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>753b0581-7492-47d1-861f-534dcb50e851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2d97b14-2fd1-469a-b349-77130c10bc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>81e16ea6-5af9-49f2-86df-57995e4a7415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c81-6 w-10rem p-inputtext p-component ng-star-inserted</value>
      <webElementGuid>ba9d2a52-ba94-4fed-96db-577ac6f79284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YY</value>
      <webElementGuid>2beb6476-ba79-4ab9-9b20-325006103af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>p-inputtext p-component</value>
      <webElementGuid>7991e7d5-e53c-4386-bb40-f71f86bacb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overflow-hidden lg:overflow-auto&quot;]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/ata-partner-invoices[@class=&quot;ng-star-inserted&quot;]/ata-invoice-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-4 hidden lg:block&quot;]/div[@class=&quot;flex align-items-center justify-content-between&quot;]/ata-invoice-export[1]/div[@class=&quot;flex align-items-center justify-content-between mb-4&quot;]/div[@class=&quot;flex-column&quot;]/form[@class=&quot;flex ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;filter-container flex flex-wrap justify-content-center p-3 gap-2 partner-filter-container&quot;]/div[@class=&quot;p-field mb-0 mr-2&quot;]/p-calendar[@class=&quot;p-element p-inputwrapper ng-tns-c81-6 ng-untouched ng-pristine ng-invalid ng-star-inserted p-inputwrapper-focus&quot;]/span[@class=&quot;ng-tns-c81-6 p-calendar p-focus&quot;]/input[@class=&quot;ng-tns-c81-6 w-10rem p-inputtext p-component ng-star-inserted&quot;]</value>
      <webElementGuid>1119cfd5-4a70-4f82-bad3-01a6ce6f4a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>4854fbf8-81d5-4612-84b2-8a935eef907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-calendar/span/input</value>
      <webElementGuid>f59ae67e-4202-44e1-ac74-f0a83eb3b225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DD/MM/YY']</value>
      <webElementGuid>141652c1-6235-4f22-90de-f10bf1da8a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
