<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to ATA Partner_p-inputtext p-_2f833e</name>
   <tag></tag>
   <elementGuidId>0d324d28-77c9-41d8-9103-a0ee0f85c2ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.ng-untouched.ng-dirty.ng-valid.p-filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df9c4f79-3417-4e11-b615-88416309c406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>05039445-d7d1-4a56-b187-8b8c07fad1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>12-3456789</value>
      <webElementGuid>a8dd7f05-976d-4f2a-9c4b-a63b51d9f461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>a9f18398-2ebe-4120-9b34-bbaf237d8fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9-]*</value>
      <webElementGuid>a2260b47-8ec4-4874-aac7-94b5a073ffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element ng-untouched ng-dirty ng-valid p-filled</value>
      <webElementGuid>0cf77573-11dc-4ffb-8544-12bfeecd81ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>[0-9-]*</value>
      <webElementGuid>6161782f-0aad-4a4a-a34d-8acd41888606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>339ef030-2a6c-4135-9713-7ae3ff0aecf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-partner[1]/ata-partner-layout-auth[@class=&quot;ng-star-inserted&quot;]/ata-partner-auth[@class=&quot;ng-star-inserted&quot;]/partner-auth-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-card lg:mt-5&quot;]/div[@class=&quot;p-4 mt-5 md:flex flex-column md:align-items-center&quot;]/form[@class=&quot;ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;p-field pb-2&quot;]/div[@class=&quot;p-inputgroup&quot;]/input[@class=&quot;p-inputtext p-component p-element ng-untouched ng-dirty ng-valid p-filled&quot;]</value>
      <webElementGuid>cdd1509e-4412-41c6-a0c5-701039c09b78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>7aa6c75e-52de-4aad-9219-9753078ae117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>3cf717e2-bea8-4149-99cc-a9382b1bb9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '12-3456789']</value>
      <webElementGuid>b130d724-0a36-44cc-b8f2-bf562d212e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
