<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verification_otp_4_5871im0x7y3lkj554v6</name>
   <tag></tag>
   <elementGuidId>a6a095b2-2c1c-44bc-9ccf-bfeda38bd818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp_4_5871im0x7y3lkj554v6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp_4_5871im0x7y3lkj554v6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e36df91-7b86-4d47-a389-385848f6885a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>7607b305-5a5f-4bea-8546-7b62f964345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>2b141458-a95d-4bba-92a5-9035e73d261b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp_4_5871im0x7y3lkj554v6</value>
      <webElementGuid>6737b32f-461a-43b0-baef-437ca4145014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>15836216-ac73-4b19-9de7-e83adae94c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>29cd2f9f-451b-425b-94e9-dfd032237aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>87e3596a-dd45-4721-ac1e-7f19beadd8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d3295556-9baf-469f-864d-8423d7560de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>4ffaef89-81c5-4ce6-9f70-575af4500f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp_4_5871im0x7y3lkj554v6&quot;)</value>
      <webElementGuid>db2640f8-4a03-4326-ae10-441fb745bd9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp_4_5871im0x7y3lkj554v6']</value>
      <webElementGuid>9428f8a1-7ed5-4c5f-a7e6-c24b2e9c1e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c_5871im0x7y3lkj554v6']/input[5]</value>
      <webElementGuid>3ed597fe-aef7-413b-8a77-a20efea8de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>6b149f0e-f150-443d-af12-f02d67ef5aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp_4_5871im0x7y3lkj554v6' and @type = 'tel']</value>
      <webElementGuid>33ab7552-9cff-4846-b11a-5a7015e047fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
