<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_otp</name>
   <tag></tag>
   <elementGuidId>2a20bcfa-2f1e-478a-b74c-bee25246cdb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/ata-partner/ata-partner-layout-auth/ata-partner-auth/partner-auth-otp/div/div/form/div[1]/ng-otp-input/div/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
