<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resolved</name>
   <tag></tag>
   <elementGuidId>34e67a4e-8ecf-4e0d-8142-d823ed7e17dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-2-label > span.p-tabview-title.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-2-label']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f29ab0d5-8052-4020-85c1-515d1270e513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-title ng-star-inserted</value>
      <webElementGuid>6e12360b-82a5-4f3b-af3f-98af1b669740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resolved</value>
      <webElementGuid>2ad36f3c-5c03-4579-ac24-ad19bd6f99e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-2-label&quot;)/span[@class=&quot;p-tabview-title ng-star-inserted&quot;]</value>
      <webElementGuid>c601e938-050a-4783-85f5-ed58ae970a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-2-label']/span</value>
      <webElementGuid>8f20e2dd-0823-4dd0-b4fd-3a0847a27ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In progress'])[1]/following::span[1]</value>
      <webElementGuid>5af73ced-66b6-4341-86f4-e7f016a11a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New case'])[1]/following::span[2]</value>
      <webElementGuid>25785221-2b2f-4d91-8fa4-324965df7799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::span[1]</value>
      <webElementGuid>aa715bf0-1127-4c2f-9bfe-49ee8884ad9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[2]</value>
      <webElementGuid>7e04fa0f-0712-4bcd-9064-d8ef882a2f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resolved']/parent::*</value>
      <webElementGuid>db5ed4b6-2699-4f6d-97cb-44fb4d6266bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a/span</value>
      <webElementGuid>68194300-10d4-4d68-9fcb-3333dece9225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Resolved' or . = 'Resolved')]</value>
      <webElementGuid>99e25f9d-64d2-446c-bebf-78ab7440a3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
