<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_ARRIVED AT CUSTOMER</name>
   <tag></tag>
   <elementGuidId>953123c2-1b54-4cca-8b1b-3a7a3e5d335c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pr_id_31_list']/p-dropdownitem[4]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>553ca47c-cb20-4c7d-84bc-f98381598e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>f25e2fa5-afb0-4a5e-ae32-df8eb37424bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARRIVED AT CUSTOMER</value>
      <webElementGuid>7000e92a-2093-4ec3-a507-8638a700d167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_31_list&quot;)/p-dropdownitem[@class=&quot;p-element ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-dropdown-item&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>bbd5efad-2cd2-4e52-a64a-5347900f8aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_31_list']/p-dropdownitem[4]/li/span</value>
      <webElementGuid>15608955-9b0c-4f0f-8d7f-ec644115ce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCEPTED'])[2]/following::span[1]</value>
      <webElementGuid>3647a10e-25c8-4b7f-a181-cff90e58045c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSIGNED'])[1]/following::span[2]</value>
      <webElementGuid>19f806d5-2c5e-430e-8de4-7f805e680288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOWING'])[1]/preceding::span[1]</value>
      <webElementGuid>af5656b3-1834-4308-bf2b-899c9cda1ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARRIVED AT WORKSHOP'])[1]/preceding::span[2]</value>
      <webElementGuid>584df453-ebdc-46a8-856f-35a424531e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ARRIVED AT CUSTOMER']/parent::*</value>
      <webElementGuid>6ca66e54-6fa1-481a-bc42-546cfd016095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[4]/li/span</value>
      <webElementGuid>7eec0c58-8059-44a8-8437-af97a6369fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ARRIVED AT CUSTOMER' or . = 'ARRIVED AT CUSTOMER')]</value>
      <webElementGuid>21f2cbed-401a-4e0f-92e1-bffc65060d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
