<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Login</name>
   <tag></tag>
   <elementGuidId>af01e7c4-cbb4-4a05-a33e-6ceb6c4c97a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='👋 Welcome!'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72dbe134-6566-42fe-9067-fd7d74de91fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>80f4f090-b436-4bb4-b908-3d17e1f9711d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>0c6b7901-1450-4c8a-9777-79b9d3c8e2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content layout-content-login&quot;]/div[@class=&quot;content-data&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;login-form ng-dirty ng-touched ng-valid&quot;]/button[@class=&quot;p-element p-button-primary p-button p-component&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>8b206085-14c7-4f6f-852d-aac742ae0fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='👋 Welcome!'])[1]/following::span[1]</value>
      <webElementGuid>3bb4bc31-5f1f-4958-801a-202fde7db55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning:'])[1]/preceding::span[1]</value>
      <webElementGuid>90e797cb-592d-4d98-a50c-0070c4300951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>25c3d810-b777-408c-86cc-a05e666d043f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>958762ba-16ed-4689-ba68-fdf1289dba7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>a4604d7c-53fe-48f1-8489-d690c916e1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
