<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username</name>
   <tag></tag>
   <elementGuidId>74790ac1-ad3f-49a2-bb20-46c2af4b84eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Username' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Username' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4716287-5b34-49a9-b522-4b91f1bb533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>6dcac893-be2e-4be7-a6e5-e0077c35fc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cc89ca0-af4d-496f-9497-12e3d92177d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>012042f1-0307-448b-888a-159d8d3fe417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c7bd55eb-0f65-4a06-83cd-bb1e9dd9e650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>f4704715-bc3d-43f7-b8ad-b83892930fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content layout-content-login&quot;]/div[@class=&quot;content-data&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;login-form ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;p-field mb-3&quot;]/input[@class=&quot;p-inputtext p-component p-element ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>1402ba1c-a3b5-4c72-96b4-9c518aa63f2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>e408bfce-447e-42cb-9dac-3ba455eca8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>14ae6f09-117e-444e-9973-0a712590ee39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Username' and @type = 'text']</value>
      <webElementGuid>f9c24212-b6ed-41d9-8e07-e7dcbbf1fa5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
