<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Activity (Input)</name>
   <tag></tag>
   <elementGuidId>138f3b09-b932-4a2a-9cff-631b4032caf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtextarea.p-inputtext.p-component.p-element.mt-1.ng-untouched.ng-dirty.ng-valid.p-filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c290b004-140a-40db-b868-008a56d916d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>33e768ba-b5f6-4d69-88f0-96684fa7d036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>a86f57c5-5d79-4a32-9903-af89e4cb259a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>2bf497cf-1389-49ba-b291-5c6221b923d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>964de38a-31a2-4269-899e-506f3671a37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please input your activity here</value>
      <webElementGuid>73920698-63fc-452c-9608-f4a7660efbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-element mt-1 ng-untouched ng-dirty ng-valid p-filled</value>
      <webElementGuid>094f536a-f37d-4579-a2dc-e7038b0058e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>5222f1fb-b9b6-4c79-9e86-fe7bbbb75be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>e14edafb-adb0-4112-817e-078fc4d46cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>93ef3155-333a-4781-96ea-3bef34e28456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;content-data&quot;]/app-case-tab[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;grid m-0 ng-star-inserted&quot;]/div[@class=&quot;w-4&quot;]/app-activities[@class=&quot;block mb-4&quot;]/p-dialog[@class=&quot;p-element ng-tns-c79-62 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c79-62 p-dialog-mask ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c79-62 p-dialog p-component p-dialog-resizable ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c79-62 p-dialog-content&quot;]/form[@class=&quot;ng-untouched ng-tns-c79-62 ng-dirty ng-valid&quot;]/div[@class=&quot;flex mb-5&quot;]/div[@class=&quot;w-full&quot;]/div[1]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-element mt-1 ng-untouched ng-dirty ng-valid p-filled&quot;]</value>
      <webElementGuid>c12e26d5-d363-4799-b070-91441cedfa28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/textarea</value>
      <webElementGuid>fb6a05c0-352e-4d07-a1f8-6b81d782260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please input your activity here']</value>
      <webElementGuid>1048c0a5-e3b5-4283-8425-3c3fa977d1da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
