<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_search_workshop</name>
   <tag></tag>
   <elementGuidId>af3b90d8-67f9-48a3-b9fa-fd10ef80bf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Workshop name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ata-input.ata-pl-12.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc06a14-fd6c-4374-883c-525377a142df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Workshop name</value>
      <webElementGuid>66d33de1-e2ea-4f1e-8e9c-ed65b1eef379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name_regex</value>
      <webElementGuid>e443edc6-6bbc-4ed2-9b9a-6327bdb04aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ata-input ata-pl-12 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5a756e55-775b-457f-938a-1d42954f5373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>name_regex</value>
      <webElementGuid>f3186283-3297-48ec-9ec0-d0421449c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/ata-workshop-directory[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ata-p-6&quot;]/ata-workshop-list[1]/ata-workshop-filter[@class=&quot;ata-mb-6&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ata-flex ata-items-center&quot;]/div[@class=&quot;ata-relative ata-grow ata-mr-6&quot;]/input[@class=&quot;ata-input ata-pl-12 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>589acff4-cc91-4d58-9de7-6446adb8ffdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6450fb36-e612-43a1-83fa-ffde80611a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Workshop name']</value>
      <webElementGuid>e94d673b-4d0c-48e4-9c04-0637acc1a933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
