<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_Inactive</name>
   <tag></tag>
   <elementGuidId>222491fc-d380-4f23-ad3e-b11c74e6c6b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pr_id_15_list']/p-dropdownitem[2]/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.customer-badge.status-Inactive.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f63c8e95-2b82-453f-ac84-bd489f905123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customer-badge status-Inactive ng-star-inserted</value>
      <webElementGuid>6997e8fe-1a18-45fd-84bd-0df9d2c9e0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>15dde1fe-c711-455f-9394-1841871c69cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_15_list&quot;)/p-dropdownitem[@class=&quot;p-element ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-dropdown-item&quot;]/span[@class=&quot;customer-badge status-Inactive ng-star-inserted&quot;]</value>
      <webElementGuid>ea4555a1-3226-4ccc-b0a8-b655805be4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_15_list']/p-dropdownitem[2]/li/span</value>
      <webElementGuid>1e18a7cd-53c8-4fdc-a8fd-9e2997a69106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::span[1]</value>
      <webElementGuid>dc9a6d48-1995-430f-89d2-34ce1ccd9aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Status'])[1]/following::span[2]</value>
      <webElementGuid>f9af64d7-03cf-4859-b552-90ae6a47307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shiun Motor Sdn Bhd (HQ)'])[1]/preceding::span[1]</value>
      <webElementGuid>faa7d131-6064-450c-942f-19a4ce2bd570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inactive']/parent::*</value>
      <webElementGuid>b72beda9-e889-4753-95ae-7e9ee8119fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li/span</value>
      <webElementGuid>eb972c50-6d08-464c-be87-0657928f1c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>daa1b1d5-788e-4b8c-80a2-63cdcda5574f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
