<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Track Now</name>
   <tag></tag>
   <elementGuidId>b1258689-4b65-4b5f-94ea-e950effc61eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ata-btn.ata-btn-primary.ata-btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e12b5767-6ac2-4d8c-b13f-c62ec2cbf0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fd41de05-7a08-48d7-9489-5b7f40203d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ata-btn ata-btn-primary ata-btn-block</value>
      <webElementGuid>2db9a188-dc4a-4e4b-b624-ba0a14005450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Track Now </value>
      <webElementGuid>b6dddda7-7d05-47ca-8eca-1d1e6534aa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/atau-tracking[@class=&quot;ng-star-inserted&quot;]/atau-tracking-verification[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ata-p-6 ng-invalid ng-touched ng-dirty&quot;]/button[@class=&quot;ata-btn ata-btn-primary ata-btn-block&quot;]</value>
      <webElementGuid>058045eb-37eb-4462-ad09-d9b25c8458cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e3f5f0b0-e108-4dc2-b889-70af5a29f7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can get the 9-digit tracking number from your SMS'])[1]/following::button[1]</value>
      <webElementGuid>5bfe59e3-9ce9-48b2-8012-303b51b83ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your vehicle number without empty space.'])[1]/following::button[1]</value>
      <webElementGuid>ad23b9d8-7e58-4805-a69d-b3a36a7bf59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>6c035552-3ac2-457f-aa2c-f6265abb254b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>b7852256-808d-4794-9025-2c74ac77fde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Track Now']/parent::*</value>
      <webElementGuid>ea4c19e2-43fe-48af-81c6-2be3314ac21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>4c6b609f-9247-4bf3-8a4f-560eab403297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Track Now ' or . = ' Track Now ')]</value>
      <webElementGuid>422346d4-3bdb-4251-b76e-68198fdf8324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
