<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input1_Track your request</name>
   <tag></tag>
   <elementGuidId>731cc54a-3b21-4480-a2b7-cbefc043f307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ata-input.ata-uppercase.ata-text-center.ata-mb-1.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1646f1b0-1a6c-4227-b98e-d108abc875e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d7c71c0-88cd-4284-b66d-18465319f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>vehicleNo</value>
      <webElementGuid>e3f07233-8d01-4ba7-ba48-19eeb6f287a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ata-input ata-uppercase ata-text-center ata-mb-1 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6136cee2-6942-4caa-90b0-f726f9b9d68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>vehicleNo</value>
      <webElementGuid>a830bded-f03c-4c97-bcd9-8b5877454b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ata-text-slate-800 ata-bg-white&quot;]/body[1]/ata-atau[1]/ata-atau-default[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;main&quot;]/atau-tracking[@class=&quot;ng-star-inserted&quot;]/atau-tracking-verification[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ata-p-6 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ata-flex ata-flex-col ata-mb-12&quot;]/input[@class=&quot;ata-input ata-uppercase ata-text-center ata-mb-1 ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>45a5db24-0ac2-4b9f-9f1a-1807880ca372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>3b43e010-4f0b-440d-ad52-9dc4636ecb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>96e70944-a17d-4ba1-93b0-884f86e98cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>83371021-e5a6-4fc7-b912-2eac99f10dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
