<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>ac81f5b8-2585-479b-ba2b-da1a5c516711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-dropdown-filter.p-inputtext.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75d9915e-c1c2-4ede-ac8f-57fe69ffa225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter vehicle model...</value>
      <webElementGuid>fac1a801-c8e8-4f81-8299-d4dafb1b31b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e7212c1-9684-4da1-9a41-e5b7dc6936dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>fb8d7fea-1b00-418a-a998-4de26f023d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-filter p-inputtext p-component</value>
      <webElementGuid>cd06627c-9fd8-4cb1-92d8-6686188f64a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>061663ae-8c2e-46a1-ad5e-8de99111e9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-dashboard-root[1]/div[@class=&quot;app-layout&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;content-data&quot;]/app-case-tab[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;flex ng-star-inserted&quot;]/div[@class=&quot;w-8 pr-5&quot;]/app-case-new[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/p-card[@class=&quot;p-element&quot;]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;p-field&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col&quot;]/p-dropdown[@class=&quot;p-element p-inputwrapper ng-pristine ng-invalid ng-star-inserted ng-touched p-inputwrapper-focus&quot;]/div[@class=&quot;w-full p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/p-overlay[@class=&quot;p-element ng-tns-c71-23 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c71-23 p-overlay p-component ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayContentAnimation ng-tns-c71-23 p-overlay-content ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-header ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-filter-container ng-star-inserted&quot;]/input[@class=&quot;p-dropdown-filter p-inputtext p-component&quot;]</value>
      <webElementGuid>72670355-0ffd-42ed-a380-99666cd44635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e18a7a3-48ca-46e9-af33-ab91ee84263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>p-highlighted-option</value>
      <webElementGuid>49502a31-8338-4955-9ff3-33d07b5944de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>e3057a57-de14-445f-82ac-9c166e14f89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-overlay/div/div/div/div/div/input</value>
      <webElementGuid>132ab15a-10ad-4194-8d3a-1aea7659318a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Filter vehicle model...']</value>
      <webElementGuid>24da077e-abc1-408d-b378-86a3415ad7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>4d084bdf-9693-4476-bc95-cd542699e0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>ee0d2851-724c-42f7-8773-8e3bee44da9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>7d288a7f-50ce-415d-88c7-fa06e94b4278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8ed19229-9680-4d88-b3f9-f7b4688d9369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Username' and @type = 'text']</value>
      <webElementGuid>33caf03b-bffe-486f-a804-7b3d79be6275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
