<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_HaziqTOWING XYZ</name>
   <tag></tag>
   <elementGuidId>dac0065b-390f-4af7-ae12-80e306c315ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.header.no-print.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>d56b64d5-10be-4e6b-9e3d-b3163ab16cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>banner</value>
      <webElementGuid>6e248096-080f-4c55-909d-3eb8b60cf10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header no-print ng-star-inserted</value>
      <webElementGuid>0415041c-86e8-4b85-a1c5-6399651eba7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HaziqTOWING XYZ</value>
      <webElementGuid>59a19f31-5fd9-4a20-b0e3-3d233a735e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ata-partner[1]/ata-partner-layout-dashboard[@class=&quot;ng-star-inserted&quot;]/header[@class=&quot;header no-print ng-star-inserted&quot;]</value>
      <webElementGuid>93bd235c-b7d9-4c03-90ed-735caa205d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>5f6fbb49-7eb9-44d2-977e-4a68a7bc97dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'HaziqTOWING XYZ' or . = 'HaziqTOWING XYZ')]</value>
      <webElementGuid>3488e63d-daf5-47e4-bec4-be2248d69ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
